### ISSUE TITLE
Train and predict in separate steps

### ISSUE THREAD

**Issue by hipoglucido** [andland/libFMexe#17]
Hello, I need the predictions of the model on the train set and also on the test set. How can I do this without having to train the model twice?
Thanks

**Comment by andland** [comment]
You unfortunately cannot save a model and predict with it later. The best I can suggest for your problem is to combine the train and test data in the prediction portion. E.g. from the README example:

``` r
train = movie_lens[train_rows, ]
test  = movie_lens[-train_rows, ]

predFM = libFM(train, rbind(train, test), Rating ~ User + Movie,
               task = "r", dim = 10, iter = 500)

# prediction on the training set
predFM[1:nrow(train)]

# predictions on the testing set
predFM[(nrow(train) + 1):(nrow(train) + nrow(test))]
```
